with open('demo/bin/nano_coverage.gdextension', 'w') as f:
    f.write('[configuration]\n')
    f.write('entry_symbol = "nano_coverage_library_init"\n')
    f.write('compatibility_minimum = "4.1"\n\n')
    f.write('[libraries]\n')
    f.write('windows.debug.x86_64 = "res://bin/nano_coverage.windows.template_debug.x86_64.dll"\n')
    f.write('windows.release.x86_64 = "res://bin/nano_coverage.windows.template_release.x86_64.dll"\n')
    f.write('linux.debug.x86_64 = "res://bin/nano_coverage.linux.template_debug.x86_64.so"\n')
    f.write('linux.release.x86_64 = "res://bin/nano_coverage.linux.template_release.x86_64.so"\n')
    f.write('macos.debug = "res://bin/nano_coverage.macos.template_debug.framework/nano_coverage"\n')
    f.write('macos.release = "res://bin/nano_coverage.macos.template_release.framework/nano_coverage"\n')
